name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: cp .env.example .env
      - run: pnpm install --frozen-lockfile=false
      - run: pnpm prisma:generate
      - run: pnpm prisma:migrate --name ci --create-only
      - run: pnpm db:seed
      - run: pnpm build
      - run: pnpm lint
      - run: pnpm test
