name: Deploy website to Pi
on:
  push: { branches: [ main ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted   # <-- simplest. (You can refine labels later.)
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to web root
        run: |
          sudo rsync -av --delete \
            --exclude '.git/' --exclude '.github/' \
            --exclude 'README.md' --exclude 'LICENSE' \
            --chown=web:web \
            ./ /var/www/owenfillmore.com/
          sudo systemctl reload caddy
